<?php

$title = 'telephone Verify';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
if (isset($error)) {
    echo $error;
} else {
    $form->setAttribute('action', $this->url('user', ['action' => 'doBindTelephone']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('telephone'));
    echo $this->formRow($form->get('smsCode'));
    ?>
    <a onclick="sendSms()">getSMS</a>
    <script language="JavaScript">
        function sendSms() {
            var telephone = $("input[name=telephone]").val();
            console.log(telephone);
            $.ajax({
                type: "POST",
                url: "<?php echo $this->url('user', ['action' => 'sendSms']) ?>",
                data: {"telephone": telephone},
                success: function (data) {
                    console.log(data);
                    alert("OK");
                },
                dataType: "text"
            });
        }
    </script>
    <?php
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
}
