<?php

$title = 'telephone Verify';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
if (isset($error)) {
    echo $error;
} else {
    $form->setAttribute('action', $this->url('user', ['action' => 'doBindTelephone']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('telephone'));
    echo $this->formRow($form->get('smsCode'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
}
