<?php

$title = 'change password';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
if (isset($error)) {
    echo $error;
} else {
    $form->setAttribute('action', $this->url('user', ['action' => 'doChangePassword']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('oldPassword'));
    echo $this->formRow($form->get('newPassword'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    echo isset($validError) ? $validError : "";
}
