<?php

$title = 'register';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('user', ['action' => 'doReg']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('passwordAgain'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo isset($error) ? $error : "";